### ISSUE TITLE
Expose constant EVENT_GOT_DEVICES

### ISSUE THREAD

**Issue by jensrossbach** [EpicKris/node-arlo#22]
**Is your feature request related to a problem? Please describe.**
Function Arlo.getDevices() emits event EVENT_GOT_DEVICES, but the constant is not accessible to clients. Clients have to use the string literal directly in order to catch the event.

**Describe the solution you'd like**
Constant `Constants.EVENT_GOT_DEVICES` should be exposed to clients.

**Comment by jensrossbach** [comment]
Is this the right way to handle issues? I.e. ignore them and then let a bot close them??

**Comment by EpicKris** [comment]
These issues are resolved as part of the upcoming `beta` branch, pull requests are welcome to solve any existing issues.
