### ISSUE TITLE
Beta Branch getDevices fails authorization

### ISSUE THREAD

**Issue by mrbythatmuch** [EpicKris/node-arlo#25]
Related to Issue #24
Header winds up with two values for Authorization which is rejected as invalid and the response error is caught in client.js  getDevices catch(error) 
 
`{
  statusCode: 401,
  result: {
    data: {
      error: "1022",
      message: "Access token is invalid.",
      reason: "Access token is invalid",
    },
    success: false,
  },
}`

Inspecting the raw header of the request for getDevices there are two authorization tokens apparently the one the is in the wrong format see issue #24 is the one being used by the server.

`{
  authorization: "21JthtSu2f4gEsGmbFFRXKza5k73Ihq_DUCj1L7G-8YrRZGq7bjdP077XYWwqN0GsOEF17xE2FAfsbo0Ih2C60IoWEFA_5tOSqZtKVYkSFJafww02TWYb0FTRFWb17EaN0dfYbNjfHz__WPLFTkLJcRMFg_LEn3Wh3byqniiiqfSi",
  accept: "application/json",
  "user-agent": "node-arlo",
  Authorization: "Basic UAFUOjJfNUp0aHRTdTJmNGdFc0dtYkZGUlhLemE1azczSWhxG0RVQ2oxTDdHLThZclJaR3E3YmpkUDA3NzRZ03dxTjBHc09FRjE3eEUyRkRmc2JvMElxMkM2MElvV0VIQV81dE9TcVp0S1ZZa1NGSmFmd3cwMlRXWWIwRlRJRldiMTdFYU4wZGZZ5k5qZkh6X19XQExiVGtMSmNSTUZnX0xFbjNXaDNieXFuaWlpcWZTaQ==",
  "X-TFS-FedAuthRedirect": "Suppress",
}`

I suspect the addtionalHeaders options below is intended to override the authorization token the PersonalAccessTokenCredentialHandler is creating???  This isn't working also would expect the authorization token is needed for more than just get devices the current web api uses the token for many of the requests depending upon the resolution of #24 the need for addtionalHeaders may go away?

`    /**
     * Get devices.
     */
    async getDevices() {
        let response;
        try {
            let options = {
                additionalHeaders: {
                    Authorization: this.handler.token
                }
            };
            response = await this.restClient.get('users/devices', options);
        } catch (error) {
            throw new Error(error);
        }
        return response.result;
    }`

**Comment by EpicKris** [comment]
The `beta` branch has an updated authentication handler, please re-open this issue if this still occurs.
