### ISSUE TITLE
General mode change notification

### ISSUE THREAD

**Issue by jensrossbach** [EpicKris/node-arlo#29]
**Is your feature request related to a problem? Please describe.**
Currently mode change notifications use the mode name as event name. This means clients need to subscribe for every possible mode in order to be notified about their activation.

**Describe the solution you'd like**
Emit a general mode change event when the mode has changed and pass the activated mode as additional argument to the event.

**Comment by EpicKris** [comment]
This has been updated to just use the `mode` event name in the `beta` branch.
