### ISSUE TITLE
Transfer Ownership Back

### ISSUE THREAD

**Issue by donavanbecker** [EpicKris/node-arlo#36]
@EpicKris, Just wondering if you are going to continue to work on this or if you want to transfer ownership back?

Haven’t seen any movement that’s why I am asking

**Comment by EpicKris** [comment]
@donavanbecker Just had a few busy months with work. I've published the changes I've made in that time and working through some of the issues now.

**Comment by donavanbecker** [comment]
Okay! Sorry just wanted to make sure this repo can continue to be developed. 

Thanks for pushing those changes!
